services:
  server:
    image: luslucifer490587/ng-proxy
    build:
      context: .
    environment:
      NODE_ENV: production
    deploy:
      replicas: 3

    # ports:
    #   - 3000:3000

  nginx:
    image: luslucifer490587/ng-cache-reverse-proxy
    build:
      context: nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx-cache:/var/cache/nginx
    depends_on:
      - server
