version: "3.8"

services:
  server:
    image: luslucifer490587/ng-proxy
    build:
      context: .
    environment:
      NODE_ENV: production
    deploy:
      replicas: 2
    restart: always

  nginx:
    image: luslucifer490587/ng-cache-reverse-proxy
    build:
      context: nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx-cache:/var/cache/nginx
    depends_on:
      - server
    restart: always

  autoheal:
    image: willfarrell/autoheal:latest
    deploy:
      replicas: 1
    environment:
      AUTOHEAL_CONTAINER_LABEL: all
    network_mode: none
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    environment:
      WATCHTOWER_LABEL_ENABLE: "true"  # Optional: Enables Watchtower label filtering
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 300  # Check for updates every 5 minutes (300 seconds)
    restart: always
