FROM nginx:alpine

# Replace default nginx config with your own
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Optional: create and set permissions for cache dir
RUN mkdir -p /var/cache/nginx && \
    chown -R nginx:nginx /var/cache/nginx

# Install wget
RUN apk add --no-cache wget

# Expose HTTP port
EXPOSE 80

# Add a health check to test the status of nginx using wget
HEALTHCHECK --interval=30s --timeout=5s --retries=3 \
  CMD wget --spider --quiet http://127.0.0.1:80/m3u8-proxy.m3u8?url=https%3A%2F%2Ftest-streams.mux.dev%2Fx36xhzz%2Fx36xhzz.m3u8&headers={} || exit 1

CMD ["nginx", "-g", "daemon off;"]
