FROM nginx:alpine

# Replace default nginx config with your own
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Optional: create and set permissions for cache dir
RUN mkdir -p /var/cache/nginx && \
    chown -R nginx:nginx /var/cache/nginx

# Expose HTTP port
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
